services:
  # Web Service
  - type: web
    name: vp-ceiling-web
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: vp-ceiling-db
          property: connectionString

  # Database
  - type: pserv
    name: vp-ceiling-db
    env: postgresql
    plan: free
    region: oregon
